package servidorNotificaciones.dto;

/**
* servidorNotificaciones/sop_corba/INotificationsManagementPackage/IndicatorsDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

public final class IndicatorsDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorNotificaciones.dto.IndicatorsDTO value;

  public IndicatorsDTOHolder ()
  {
  }

  public IndicatorsDTOHolder (servidorNotificaciones.dto.IndicatorsDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorNotificaciones.dto.IndicatorsDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        servidorNotificaciones.dto.IndicatorsDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorNotificaciones.dto.IndicatorsDTOHelper.type ();
  }

}
