package servidorNotificaciones.dto;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementPackage/NotificationDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Friday, March 27, 2020 4:20:49 PM COT
*/

public final class NotificationDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int roomNumber;
  public String nameComplete;
  public String age ;
  public String hour ;
  public String date ;
  public String message;
  public String indicators[] ;
  public String lastFiveAlerts[];

  public NotificationDTO ()
  {
  } // ctor

  public NotificationDTO (int _roomNumber, String _nameComplete, String _age, String _hour, String _date, String _message, String[] _indicators, String[] _lastFiveAlerts)
  {
    roomNumber = _roomNumber;
    nameComplete = _nameComplete;
    age = _age;
    hour = _hour;
    date = _date;
    message = _message;
    indicators = _indicators;
    lastFiveAlerts = _lastFiveAlerts;
  } // ctor

} // class NotificationDTO
