package servidorNotificaciones.dto;

import java.util.ArrayList;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementPackage/NotificationDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

public final class NotificationDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String name ;
  public String lastname;
  public int roomNumber = (int)0;
  public String age;
  public String message ;
  public servidorNotificaciones.dto.IndicatorsDTO indicators ;

  public NotificationDTO ()
  {
  } // ctor

  public NotificationDTO (String _name, String _lastname, int _roomNumber, String _age, String _message, servidorNotificaciones.dto.IndicatorsDTO _indicators)
  {
    name = _name;
    lastname = _lastname;
    roomNumber = _roomNumber;
    age = _age;
    message = _message;
    indicators = _indicators;
  } // ctor

    public NotificationDTO(String toString, String toString0, String toString1, String toString2, String toString3, String toString4, String toString5, ArrayList<String> indicadoresAlerta, ArrayList<String> ultimasCincoAlertas) {
        System.out.println(toString);
    }

} // class NotificationDTO
