package servidorNotificaciones.dto;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementPackage/NotificationDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

abstract public class NotificationDTOHelper
{
  private static String  _id = "IDL:sop_corba/INotificationsManagement/NotificationDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, servidorNotificaciones.dto.NotificationDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidorNotificaciones.dto.NotificationDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "lastname",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "roomNumber",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "age",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "message",
            _tcOf_members0,
            null);
          _tcOf_members0 = servidorNotificaciones.dto.IndicatorsDTOHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "indicators",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (servidorNotificaciones.dto.NotificationDTOHelper.id (), "NotificationDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidorNotificaciones.dto.NotificationDTO read (org.omg.CORBA.portable.InputStream istream)
  {
        servidorNotificaciones.dto.NotificationDTO value = new servidorNotificaciones.dto.NotificationDTO ();
    value.name = istream.read_string ();
    value.lastname = istream.read_string ();
    value.roomNumber = istream.read_long ();
    value.age = istream.read_string ();
    value.message = istream.read_string ();
    value.indicators = servidorNotificaciones.dto.IndicatorsDTOHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidorNotificaciones.dto.NotificationDTO value)
  {
    ostream.write_string (value.name);
    ostream.write_string (value.lastname);
    ostream.write_long (value.roomNumber);
    ostream.write_string (value.age);
    ostream.write_string (value.message);
        servidorNotificaciones.dto.IndicatorsDTOHelper.write (ostream, value.indicators);
  }

}
