package servidorAlertas.dto;


/**
* servidorAlertas/sop_corba/IPatientManagementPackage/IndicatorsDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Wednesday, March 25, 2020 6:31:50 PM COT
*/

public final class IndicatorsDTO implements org.omg.CORBA.portable.IDLEntity
{
  public double cardiacFrequency = (double)0;
  public double systolicBloodPressure = (double)0;
  public double diastolicBloodpressure = (double)0;
  public double breathingFrequency = (double)0;
  public double oxigenSaturation = (double)0;
  public double temperature = (double)0;

  public IndicatorsDTO ()
  {
  } // ctor

  public IndicatorsDTO (double _cardiacFrequency, double _systolicBloodPressure, double _diastolicBloodpressure, double _breathingFrequency, double _oxigenSaturation, double _temperature)
  {
    cardiacFrequency = _cardiacFrequency;
    systolicBloodPressure = _systolicBloodPressure;
    diastolicBloodpressure = _diastolicBloodpressure;
    breathingFrequency = _breathingFrequency;
    oxigenSaturation = _oxigenSaturation;
    temperature = _temperature;
  } // ctor

} // class IndicatorsDTO
