package servidorAlertas.dto;

import servidorAlertas.sop_corba.IPatientCallback;


/**
* servidorAlertas/sop_corba/IPatientManagementPackage/PatientDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Friday, March 27, 2020 5:05:35 PM COT
*/

public final class PatientDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int roomNumber ;
  public String name ;
  public String lastname ;
  public String birthday;
  public String age ;
  public servidorAlertas.dto.IndicatorsDTO indicators;
  public servidorAlertas.sop_corba.IPatientCallback patientClbk ;

  public PatientDTO ()
  {
  } // ctor

  public PatientDTO (String _name, String _lastname, int _roomNumber, String _birthday, String _age, servidorAlertas.dto.IndicatorsDTO _indicators, servidorAlertas.sop_corba.IPatientCallback _patientClbk)
  {
    name = _name;
    lastname = _lastname;
    roomNumber = _roomNumber;
    birthday = _birthday;
    age = _age;
    indicators = _indicators;
    patientClbk = _patientClbk;
  } // ctor

    public PatientDTO(int roomNumber, String name, String lastname, String birthday) {
             this.name = name;
        this.lastname = lastname;
        this.roomNumber = roomNumber;
        this.birthday = birthday;
           this.age="";
        this.indicators= new IndicatorsDTO();
        this.patientClbk = patientClbk;
    }



    public PatientDTO(String name, String lastname, int roomNumber, String birthday, IPatientCallback patientClbk) {
        this.name = name;
        this.lastname = lastname;
        this.roomNumber = roomNumber;
        this.birthday = birthday;
           this.age="";
        this.indicators= new IndicatorsDTO();
        this.patientClbk = patientClbk;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public int getRoomNumber() {
        return roomNumber;
    }

    public void setRoomNumber(int roomNumber) {
        this.roomNumber = roomNumber;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public IndicatorsDTO getIndicators() {
        return indicators;
    }

    public void setIndicators(IndicatorsDTO indicators) {
        this.indicators = indicators;
    }

    public IPatientCallback getPatientClbk() {
        return patientClbk;
    }

    public void setPatientClbk(IPatientCallback patientClbk) {
        this.patientClbk = patientClbk;
    }

    @Override
    public String toString() {
        return roomNumber + ","+name + "," + lastname + "," + birthday + "," + age + "," + indicators + "," + patientClbk;
    }

} // class PatientDTO
