package servidorAlertas.dto;


/**
* servidorAlertas/sop_corba/IPatientManagementPackage/PatientDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Thursday, March 26, 2020 4:29:02 PM COT
*/

abstract public class PatientDTOHelper
{
  private static String  _id = "IDL:sop_corba/IPatientManagement/PatientDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, servidorAlertas.dto.PatientDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidorAlertas.dto.PatientDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "lastname",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "roomNumber",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "birthday",
            _tcOf_members0,
            null);
          _tcOf_members0 = servidorAlertas.dto.IndicatorsDTOHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "indicators",
            _tcOf_members0,
            null);
          _tcOf_members0 = servidorAlertas.sop_corba.IPatientCallbackHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "patientClbk",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (servidorAlertas.dto.PatientDTOHelper.id (), "PatientDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidorAlertas.dto.PatientDTO read (org.omg.CORBA.portable.InputStream istream)
  {
        servidorAlertas.dto.PatientDTO value = new servidorAlertas.dto.PatientDTO ();
    value.name = istream.read_string ();
    value.lastname = istream.read_string ();
    value.roomNumber = istream.read_long ();
    value.birthday = istream.read_string ();
    value.indicators = servidorAlertas.dto.IndicatorsDTOHelper.read (istream);
    value.patientClbk = servidorAlertas.sop_corba.IPatientCallbackHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidorAlertas.dto.PatientDTO value)
  {
    ostream.write_string (value.name);
    ostream.write_string (value.lastname);
    ostream.write_long (value.roomNumber);
    ostream.write_string (value.birthday);
        servidorAlertas.dto.IndicatorsDTOHelper.write (ostream, value.indicators);
    servidorAlertas.sop_corba.IPatientCallbackHelper.write (ostream, value.patientClbk);
  }

}
