module sop_corba{
	interface NotificationsManagement{

		struct Indicators{
			double cardiacFrequency;
			double systolicBloodPressure;
			double DiastolicBloodpressure;
			double breathingFrequency;
			double oxigenSaturation;
			double temperature;
		};
		struct NotificationDTO{
			string name;
			string lastname;
			long roomNumber;
			string age;
			string message;
			Indicators listIndicators;

		};
		boolean notifyAlert(in NotificationDTO objNotification);
		

	};
};