CREATE TABLE `db_alerts`.`patient` ( `roomID` INT(255) NOT NULL , `name` VARCHAR(100) NOT NULL , `lastname` VARCHAR(100) NOT NULL , `birthday` VARCHAR(100) NOT NULL , PRIMARY KEY (`roomID`)) ENGINE = InnoDB;

CREATE TABLE `db_alerts`.`alerts` ( `roomIDAlert` INT(100) NOT NULL , `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
ON UPDATE CURRENT_TIMESTAMP NOT NULL , `score` INT(100) NOT NULL ) ENGINE = InnoDB;
