package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/INotificationsManagement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

public interface INotificationsManagement extends INotificationsManagementOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface INotificationsManagement
