package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

public interface INotificationsManagementOperations 
{
  boolean notifyAlert (servidorNotificaciones.dto.NotificationDTO objNotification);
} // interface INotificationsManagementOperations
