package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

public abstract class INotificationsManagementPOA extends org.omg.PortableServer.Servant
 implements servidorNotificaciones.sop_corba.INotificationsManagementOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyAlert", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/INotificationsManagement/notifyAlert
       {
         servidorNotificaciones.dto.NotificationDTO objNotification = servidorNotificaciones.dto.NotificationDTOHelper.read (in);
         boolean $result = false;
         $result = this.notifyAlert (objNotification);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/INotificationsManagement:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public INotificationsManagement _this() 
  {
    return INotificationsManagementHelper.narrow(
    super._this_object());
  }

  public INotificationsManagement _this(org.omg.CORBA.ORB orb) 
  {
    return INotificationsManagementHelper.narrow(
    super._this_object(orb));
  }


} // class INotificationsManagementPOA
