package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Friday, March 27, 2020 4:20:49 PM COT
*/

public interface INotificationsManagementOperations 
{
  boolean notifyAlert (servidorNotificaciones.dto.NotificationDTO objNotification);
} // interface INotificationsManagementOperations
