package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/INotificationsManagementPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Friday, March 27, 2020 4:20:49 PM COT
*/

public class INotificationsManagementPOATie extends INotificationsManagementPOA
{

  // Constructors

  public INotificationsManagementPOATie ( servidorNotificaciones.sop_corba.INotificationsManagementOperations delegate ) {
      this._impl = delegate;
  }
  public INotificationsManagementPOATie ( servidorNotificaciones.sop_corba.INotificationsManagementOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorNotificaciones.sop_corba.INotificationsManagementOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorNotificaciones.sop_corba.INotificationsManagementOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean notifyAlert (servidorNotificaciones.dto.NotificationDTO objNotification)
  {
    return _impl.notifyAlert(objNotification);
  } // notifyAlert

  private servidorNotificaciones.sop_corba.INotificationsManagementOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class INotificationsManagementPOATie
