package servidorNotificaciones.sop_corba;

/**
* servidorNotificaciones/sop_corba/INotificationsManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Notifications.idl
* Wednesday, March 25, 2020 1:11:47 PM COT
*/

public final class INotificationsManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorNotificaciones.sop_corba.INotificationsManagement value = null;

  public INotificationsManagementHolder ()
  {
  }

  public INotificationsManagementHolder (servidorNotificaciones.sop_corba.INotificationsManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorNotificaciones.sop_corba.INotificationsManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorNotificaciones.sop_corba.INotificationsManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorNotificaciones.sop_corba.INotificationsManagementHelper.type ();
  }

}
