/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteHabitacion.vistas;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import servidorAlertas.dto.PatientDTO;

/**
 *
 * @author dawish
 */
public class UpdateGUI extends javax.swing.JDialog {

    /**
     * Creates new form UpdateGUI
     */
    public UpdateGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDataBirthday = new com.toedter.calendar.JDateChooser();
        txtName = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHabitacion = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblmgsNameError = new javax.swing.JLabel();
        lblmgsLastnameError = new javax.swing.JLabel();
        lblmgsRoomError = new javax.swing.JLabel();
        lblmgsDateError = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblReply = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("Registar Paciente");
        jPanel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        jLabel1.setText("Nombres: ");

        jLabel2.setText("Apellidos: ");

        jLabel3.setText("Fecha de nacimiento: ");

        jLabel4.setText("N° de habitacion: ");

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblmgsNameError.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        lblmgsNameError.setText("jLabel5");

        lblmgsLastnameError.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        lblmgsLastnameError.setText("jLabel5");

        lblmgsRoomError.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        lblmgsRoomError.setText("jLabel5");

        lblmgsDateError.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        lblmgsDateError.setText("jLabel5");

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblReply.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jDataBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(lblmgsNameError)
                                    .addComponent(lblmgsLastnameError))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(txtLastname)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmgsRoomError)
                                    .addComponent(lblmgsDateError)
                                    .addComponent(jLabel3)
                                    .addComponent(lblReply))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHabitacion)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(5, 5, 5)
                .addComponent(lblmgsNameError)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblmgsLastnameError)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDataBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmgsDateError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmgsRoomError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReply)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void clearLabels() {
        this.lblmgsNameError.setText("");
        this.lblmgsLastnameError.setText("");
        this.lblmgsRoomError.setText("");
        this.lblmgsDateError.setText("");
    }

    private boolean isNumeric(String parametro) {
        try {
            Integer.parseInt(parametro);
            return true;
        } catch (NumberFormatException nfe) {
            return false;

        }
    }

    private boolean validarDatosDeEntrada() {

        if (!isNumeric(this.txtHabitacion.getText())) {
            this.lblmgsRoomError.setForeground(Color.red);
            this.lblmgsRoomError.setText("Ups!!! el numero de habitacion debe ser un entero");
            return false;
        } else if (isNumeric(this.txtName.getText())) {
            this.lblmgsNameError.setForeground(Color.red);
            this.lblmgsNameError.setText("Ups!!! el Nombre debe ser en letras");
            return false;
        } else if (isNumeric(this.txtLastname.getText())) {
            this.lblmgsLastnameError.setForeground(Color.red);
            this.lblmgsLastnameError.setText("Ups!!! el Apellido debe ser en letras");
            return false;
        } else {
            return true;
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (this.txtName.getText().length() != 0 && this.txtLastname.getText().length() != 0 && this.txtHabitacion.getText().length() != 0 && this.jDataBirthday.getDate() != null) {

            if (validarDatosDeEntrada()) {

                int habitacion = Integer.parseInt(this.txtHabitacion.getText());
                if (habitacion <= 100 || habitacion > 999) {
                    this.lblmgsRoomError.setForeground(Color.red);
                    this.lblmgsRoomError.setText("Ups!!! el numero de habitacion debe estar entre 100 y 999");
                } else {

                    Date fecha = jDataBirthday.getDate();
                    DateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                    String fecha2 = f.format(fecha);

                    PatientDTO patient = new PatientDTO(this.txtName.getText(), this.txtLastname.getText(), Integer.parseInt(this.txtHabitacion.getText()), fecha2);
                    patient.setPatientClbk(RoomGUI.patient);
                    boolean reply=RoomGUI.ref.modifyPatient(Integer.parseInt(this.txtHabitacion.getText()),patient);
               
                    if (reply) {
                        clearLabels();
                        this.lblReply.setForeground(Color.green);
                        this.lblReply.setText("Paciente actualizado");
                    }
                    else{
                        this.lblReply.setForeground(Color.red);
                        this.lblReply.setText("Fallido en la actualización: no se contacto el servidor");
                    }
                }
            }

        } else {
            if (this.txtName.getText().length() == 0) {
                this.lbl1.setForeground(Color.red);
                this.lbl1.setText("*");
            }
            if (this.txtLastname.getText().length() == 0) {
                this.lbl2.setForeground(Color.red);
                this.lbl2.setText("*");
            }
            if (this.txtHabitacion.getText().length() == 0) {
                this.lbl3.setForeground(Color.red);
                this.lbl3.setText("*");
            }
            if (this.jDataBirthday.getDate() == null) {
                this.lbl4.setForeground(Color.red);
                this.lbl4.setText("*");
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser jDataBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblReply;
    private javax.swing.JLabel lblmgsDateError;
    private javax.swing.JLabel lblmgsLastnameError;
    private javax.swing.JLabel lblmgsNameError;
    private javax.swing.JLabel lblmgsRoomError;
    private javax.swing.JTextField txtHabitacion;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
