package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/_IPatientManagementStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Friday, March 27, 2020 3:10:22 PM COT
*/

public class _IPatientManagementStub extends org.omg.CORBA.portable.ObjectImpl implements servidorAlertas.sop_corba.IPatientManagement
{

  public boolean registerPatient (servidorAlertas.dto.PatientDTO objPatient)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerPatient", true);
                servidorAlertas.dto.PatientDTOHelper.write ($out, objPatient);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerPatient (objPatient        );
            } finally {
                _releaseReply ($in);
            }
  } // registerPatient

  public boolean findPatient (int roomId, servidorAlertas.dto.PatientDTOHolder objPatient)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findPatient", true);
                $out.write_long (roomId);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objPatient.value = servidorAlertas.dto.PatientDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findPatient (roomId, objPatient        );
            } finally {
                _releaseReply ($in);
            }
  } // findPatient

  public boolean modifyPatient (int roomId, servidorAlertas.dto.PatientDTO objPatientModified)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifyPatient", true);
                $out.write_long (roomId);
                servidorAlertas.dto.PatientDTOHelper.write ($out, objPatientModified);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modifyPatient (roomId, objPatientModified        );
            } finally {
                _releaseReply ($in);
            }
  } // modifyPatient

  public String[] selectAllPatients (servidorAlertas.sop_corba.IPatientCallback callback)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("selectAllPatients", true);
                servidorAlertas.sop_corba.IPatientCallbackHelper.write ($out, callback);
                $in = _invoke ($out);
                String $result[] = servidorAlertas.dto.PatientsListDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return selectAllPatients (callback        );
            } finally {
                _releaseReply ($in);
            }
  } // selectAllPatients

  public boolean sendIndicators (int roomId, servidorAlertas.dto.IndicatorsDTO indicators)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendIndicators", true);
                $out.write_long (roomId);
                servidorAlertas.dto.IndicatorsDTOHelper.write ($out, indicators);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sendIndicators (roomId, indicators        );
            } finally {
                _releaseReply ($in);
            }
  } // sendIndicators

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/IPatientManagement:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IPatientManagementStub
