package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Friday, March 27, 2020 3:10:22 PM COT
*/

public interface IPatientCallback extends IPatientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatientCallback
