package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Friday, March 27, 2020 5:05:35 PM COT
*/

public interface IPatientManagementOperations 
{
  boolean registerPatient (servidorAlertas.dto.PatientDTO objPatient);
  boolean findPatient (int roomId, servidorAlertas.dto.PatientDTOHolder objPatient);
  boolean modifyPatient (int roomId, servidorAlertas.dto.PatientDTO objPatientModified);
  String[] selectAllPatients ();
  boolean sendIndicators (int roomId, servidorAlertas.dto.IndicatorsDTO indicators, servidorAlertas.sop_corba.IPatientCallback callback);
} // interface IPatientManagementOperations
