package servidorAlertas.sop_corba;

/**
* servidorAlertas/sop_corba/IPatientManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Thursday, March 26, 2020 4:29:02 PM COT
*/

public final class IPatientManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorAlertas.sop_corba.IPatientManagement value = null;

  public IPatientManagementHolder ()
  {
  }

  public IPatientManagementHolder (servidorAlertas.sop_corba.IPatientManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorAlertas.sop_corba.IPatientManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorAlertas.sop_corba.IPatientManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorAlertas.sop_corba.IPatientManagementHelper.type ();
  }

}
