package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientManagementPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Friday, March 27, 2020 5:05:35 PM COT
*/

public class IPatientManagementPOATie extends IPatientManagementPOA
{

  // Constructors

  public IPatientManagementPOATie ( servidorAlertas.sop_corba.IPatientManagementOperations delegate ) {
      this._impl = delegate;
  }
  public IPatientManagementPOATie ( servidorAlertas.sop_corba.IPatientManagementOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorAlertas.sop_corba.IPatientManagementOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorAlertas.sop_corba.IPatientManagementOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean registerPatient (servidorAlertas.dto.PatientDTO objPatient)
  {
    return _impl.registerPatient(objPatient);
  } // registerPatient

  public boolean findPatient (int roomId, servidorAlertas.dto.PatientDTOHolder objPatient)
  {
    return _impl.findPatient(roomId, objPatient);
  } // findPatient

  public boolean modifyPatient (int roomId, servidorAlertas.dto.PatientDTO objPatientModified)
  {
    return _impl.modifyPatient(roomId, objPatientModified);
  } // modifyPatient

  public String[] selectAllPatients ()
  {
    return _impl.selectAllPatients();
  } // selectAllPatients

  public boolean sendIndicators (int roomId, servidorAlertas.dto.IndicatorsDTO indicators, servidorAlertas.sop_corba.IPatientCallback callback)
  {
    return _impl.sendIndicators(roomId, indicators, callback);
  } // sendIndicators

  private servidorAlertas.sop_corba.IPatientManagementOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class IPatientManagementPOATie
