package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientManagement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Wednesday, March 25, 2020 6:31:50 PM COT
*/

public interface IPatientManagement extends IPatientManagementOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatientManagement
