package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Wednesday, March 25, 2020 6:31:50 PM COT
*/

public abstract class IPatientCallbackPOA extends org.omg.PortableServer.Servant
 implements servidorAlertas.sop_corba.IPatientCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyAlert", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/IPatientCallback/notifyAlert
       {
         int roomNumber = in.read_long ();
         String message = in.read_string ();
         String $result = null;
         $result = this.notifyAlert (roomNumber, message);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/IPatientCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IPatientCallback _this() 
  {
    return IPatientCallbackHelper.narrow(
    super._this_object());
  }

  public IPatientCallback _this(org.omg.CORBA.ORB orb) 
  {
    return IPatientCallbackHelper.narrow(
    super._this_object(orb));
  }


} // class IPatientCallbackPOA
