package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Friday, March 27, 2020 3:10:22 PM COT
*/

public interface IPatientCallbackOperations 
{
  String notifyAlert (int roomNumber, String message);
} // interface IPatientCallbackOperations
