package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Thursday, March 26, 2020 4:29:02 PM COT
*/

public interface IPatientCallback extends IPatientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatientCallback
