package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Thursday, March 26, 2020 4:29:02 PM COT
*/

public interface IPatientManagementOperations 
{
  boolean registerPatient (servidorAlertas.dto.PatientDTO objPatient);
  boolean findPatient (int roomId, servidorAlertas.dto.PatientDTOHolder objPatient);
  boolean modifyPatient (int roomId, servidorAlertas.dto.PatientDTO objPatientModified);
  boolean selectPatient (int roomId, servidorAlertas.dto.PatientDTOHolder objPatientSelected);
  String[] selectAllPatients ();
  boolean sendIndicators (int roomId, servidorAlertas.dto.IndicatorsDTO indicators);
} // interface IPatientManagementOperations
