package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/IPatientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatientManagement.idl
* Wednesday, March 25, 2020 6:31:50 PM COT
*/

public interface IPatientCallbackOperations 
{
  String notifyAlert (int roomNumber, String message);
} // interface IPatientCallbackOperations
